### PR TITLE
Added Redis webhook docs

### PR DESCRIPTION
**Pull request by m1ome**
@tidwall

### CODE REVIEW

**Comment by tidwall** [comment]
Thanks for doing this. One thing though, when working with the website you'll need to edit the files in the src directory and then run ./build.sh to generate the website. You can also run "./build.sh -port 8080" to build and spin up a test server that watches for changes.

**Comment by m1ome** [comment]
@tidwall done.

**Comment by tidwall** [comment]
Looks great. Thanks!

**Comment by m1ome** [comment]
@tidwall you are welcome!

**Pull request merged**
